# ========================================================================= #
# TestR Framework Copyright © 2022 Berkant Yüksektepe                       #
# Licensed under the MIT License.                                           #
# ========================================================================= #

parameters: 

  - name: Jmeter-version
    type: string
    value: 5.5
    
  - name: test-type
    type: string
    value: load
  
    
  