# ========================================================================= #
# TestR Framework Copyright © 2022 Berkant Yüksektepe                       #
# Licensed under the MIT License.                                           #
# ========================================================================= #
---
configs: 

  - name: Jmeter-version
    type: string
    value: 5.5
    pre-options: 5.2, 5.5
    
  - name: test-type
    type: string
    value: load
    pre-options: performance, load
---
  
    
  